// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "09d1fbbc54b13cfb58a6657e071b0a71"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"f4f2f5c075d5a741ea6080317bc2ce94": "1f8b08000000000000ff8cd1cd6aeb400c05e0bd9e42cb7b69f3045985c68582e396d45e9bb1ad04d1f931922669debe346ec0a50de9acb4f8381a74160bbc0bbc176784cd08d00b7d8ee63a4f68e2a2bade3845857f8088c803ce5ec77b2561e771140e4e4ef846a7fb33548a03c9051abddb34c56418b3f79312ea890f17774db99072b45b596aceb2dedc38fffff5ac3fa9c337157320e1fe87626dfbac9642bb23c22e25ff5bd674f8a175e74dc681d45c18b17aaeb16aca12d7c5e3aa296b7c68b6dba2aadbfa6953bcd6abcd0bfc5f02cc7b5ca7630418248d5f3dee7c3aea1200e0230000ffff79592ea6ef010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f4f2f5c075d5a741ea6080317bc2ce94"})
	}()
	return nil
}()
