// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "09d1fbbc54b13cfb58a6657e071b0a71"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"f4f2f5c075d5a741ea6080317bc2ce94": "1f8b08000000000000ff8cd2cf4ac3401006f0fb3cc51c152d88d79e8a8d20a451eae61c36c9b42cee9f3033a9f6eda50d95540c714f73f831ecb7fb2d167817dc9ead12961d40c3741ad5d69e50d946d9110bdc0022a26b71746ab71762673d76ec82e5237ed0f1fe0c85624b7c814a5f3a4c3129c6defb413135e40e1737a56c487dd4b95da2567b99533ba251802945dc3c3ecc2a1ebfc5f4bdfea50e57cafdc4bd564eaaa6174da13ae5a853f27fa9e107dbca9e97a80b246a4387c5abc1a2cc735c67cfab3237f8546eb759612af3b2c9decd6af306b74b807121d6e93302b49cbadf855802007c070000ffff1c50ebd13c020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f4f2f5c075d5a741ea6080317bc2ce94"})
	}()
	return nil
}()
